alter table QUIZRESULT
add Constraint QRAFK Foreign Key (QUESTIONID, ANSWERID)
REFERENCES QUESTIONANSWER(QUESTIONID, ANSWERID)

alter table QUIZRESULT
drop PRIMARY KEY

alter table QUIZRESULT
add Constraint QRPK PRIMARY KEY (QUIZID, QUESTIONID, USERID)