/*
 * Helper.DbAccess is used to get the arraylist which stores the questions.
 * 
 * 
 */

package QuizGeneration;

import Helper.DbAccess;
import QuizApp.Core.Question;
import QuizApp.Core.Quiz;

import java.awt.Toolkit;
import java.awt.*;
import java.awt.event.*;
import java.util.List;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.ActionEvent;
import java.awt.BorderLayout;

import javax.swing.*;
import javax.swing.event.*;
/**
 *
 * @author dean
 */

	
public class QuizGenerationForm extends javax.swing.JPanel implements ActionListener 
{
    private Boolean ShowPracticeQuestion = false;
    private Boolean NavigationEnabled  = false;
    private Boolean TimeAllotted = false;
    private String TitleEntry;
    private int TimeAllottedField;
    private JLabel status;
    
    
    

    /**
     * Creates new form QuizGenerationForm
     */
    public QuizGenerationForm() {
        initComponents();
        
        //Quit_button.addActionListener( this );
       
        //TakeQuiz_button.addActionListener( this );
        TimeAllotted_chkbox.addActionListener( this );
        

    }
    public void GenerateQuiz()
    {
       TitleEntry = TitleEntry_textbox.getText();
       Quiz newQuiz = new Quiz(TitleEntry);
       newQuiz.navigationEnabled = NavigationEnabled_chkbox.isSelected();
       newQuiz.showPracticeQuestion = ShowPracticeQuestion_chkbox.isSelected();
       String enteredTime = TimeAllottedField_text.getText();
       if (enteredTime.equals(""))
       {
           newQuiz.timeLimit = 0;
       }
       else
       {
           newQuiz.timeLimit = Integer.parseInt(enteredTime);
       }
       newQuiz.randomiseQuestions = true;
       newQuiz.timeOutBehaviour = 1;
       newQuiz.quizDBId = DbAccess.CreateQuiz(newQuiz);
       
       List<Question> allValidatedQuestions = DbAccess.getAllQuestions(true);
       
       for (Question q : allValidatedQuestions)
       {
           DbAccess.ToggleQuizQuestionLink(newQuiz.quizDBId, q.dbId, true);
       }
       
       
       
       
        
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        QuizTitle = new javax.swing.JLabel();
        RandomGeneration_button = new javax.swing.JButton();
        TakeQuiz_button = new javax.swing.JButton();
        Quit_button = new javax.swing.JButton();
        ShowPracticeQuestion_chkbox = new javax.swing.JCheckBox();
        NavigationEnabled_chkbox = new javax.swing.JCheckBox();
        TimeAllotted_chkbox = new javax.swing.JCheckBox();
        
        TimeAllottedField_text = new javax.swing.JTextField();
        TimeAllottedField_text.setEditable(false);
        TitleEntry_textbox = new javax.swing.JTextField();

        QuizTitle.setText("Quiz Generation Menu");

        RandomGeneration_button.setText("Random Generation");
        RandomGeneration_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomGeneration_buttonActionPerformed(evt);
            }
        });
        TimeAllotted_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeAllotted_chkboxActionPerformed(evt);
            }
        });

        TakeQuiz_button.setText("Take Quiz");

        Quit_button.setText("Quit");

        ShowPracticeQuestion_chkbox.setText("Show practice question");
        ShowPracticeQuestion_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPracticeQuestion_chkboxActionPerformed(evt);
            }
        });

        NavigationEnabled_chkbox.setText("Navigation Enabled");

        TimeAllotted_chkbox.setText("Time allotted");
        TimeAllotted_chkbox.setActionCommand("Time allotted");

        TitleEntry_textbox.setText("Enter a title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NavigationEnabled_chkbox)
                            .addComponent(ShowPracticeQuestion_chkbox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TimeAllotted_chkbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TimeAllottedField_text, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitleEntry_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(QuizTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Quit_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RandomGeneration_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TakeQuiz_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizTitle)
                .addGap(27, 27, 27)
                .addComponent(TitleEntry_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowPracticeQuestion_chkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavigationEnabled_chkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeAllotted_chkbox)
                    .addComponent(TimeAllottedField_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RandomGeneration_button)
                    .addComponent(Quit_button)
                    .addComponent(TakeQuiz_button))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>                        
    private void TimeAllotted_chkboxActionPerformed(java.awt.event.ActionEvent evt) {  
        
			if(TimeAllottedField_text.isEditable()){
				TimeAllottedField_text.setEditable(false);
				status.setText("Field is No Longer Editable");
			} else if(!TimeAllottedField_text.isEditable()){
				TimeAllottedField_text.setEditable(true);
                    }
		
    }

    private void RandomGeneration_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        //this.GenerateQuiz();

				if(JOptionPane.showConfirmDialog(null, "Are you sure?")==0){
					GenerateQuiz();
					status.setText("Quiz generated");
				}
			}
				
     
    
    

    private void ShowPracticeQuestion_chkboxActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           


    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox NavigationEnabled_chkbox;
    private javax.swing.JButton Quit_button;
    private javax.swing.JLabel QuizTitle;
    private javax.swing.JButton RandomGeneration_button;
    private javax.swing.JCheckBox ShowPracticeQuestion_chkbox;
    private javax.swing.JButton TakeQuiz_button;
    private javax.swing.JTextField TimeAllottedField_text;
    private javax.swing.JCheckBox TimeAllotted_chkbox;
    private javax.swing.JTextField TitleEntry_textbox;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
      
        
    }
}
